"""

Pentagonal numbers are generated by the formula, 
Pn=n(3n-1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. 
However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, 
for which their sum and difference are pentagonal 
and D = |Pk - Pj| is minimised; what is the value of D?
"""
from Helper import isPentagonal
import sys

def pentagonal(n):
	return n*(3*n-1)/2

k = 2
minD = 10**10
while True:
	for j in range(k-1, 0, -1):
		pk = pentagonal(k)
		pj = pentagonal(j)

		if pk - pj < minD:
			if isPentagonal(pk-pj) and isPentagonal(pk+pj):
				minD = pk-pj
				sys.exit(0)
	k += 1

